export default {
  LOAD_USER: 'LOAD_USER',
  LOAD_USER_SUCCESS: 'LOAD_USER_SUCCESS',
  LOAD_USER_ERROR: 'LOAD_USER_ERROR',
  CREATE_TODO: 'CREATE_TODO',
  CREATE_TODO_SUCCESS: 'CREATE_TODO_SUCCESS',
  CREATE_TODO_ERROR: 'CREATE_TODO_ERROR',
  UPDATE_TODO: 'UPDATE_TODO',
  UPDATE_TODO_SUCCESS: 'UPDATE_TODO_SUCCESS',
  UPDATE_TODO_ERROR: 'UPDATE_TODO_ERROR',
  DELETE_TODO: 'DELETE_TODO',
  DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
  DELETE_TODO_ERROR: 'DELETE_TODO_ERROR',
  LOAD_TODOS: 'LOAD_TODOS',
  LOAD_TODOS_SUCCESS: 'LOAD_TODOS_SUCCESS',
  LOAD_TODOS_ERROR: 'LOAD_TODOS_ERROR',
  TOGGLE_TODO: 'TOGGLE_TODO',
  SAVED_TODO: 'SAVED_TODO'
};
